In [13]:
import pandas as pd
df = pd.read_csv("/Users/goldyrana/mess/deep_learning/projects/telco_customer_churn/data/interim/test/test.csv", na_values='', na_filter='')

In [14]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,5180-UCIIQ,Male,1,Yes,Yes,22,No,No phone service,DSL,Yes,...,No,No,No,Yes,Month-to-month,No,Mailed check,40.05,880.2,Yes
1,8868-WOZGU,Male,0,No,No,28,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,105.70,2979.5,Yes
2,5012-YSPJJ,Male,0,Yes,Yes,31,Yes,No,DSL,No,...,Yes,Yes,No,No,Month-to-month,No,Mailed check,54.35,1647,No
3,7225-CBZPL,Male,1,Yes,No,17,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,94.80,1563.9,No
4,0334-ZFJSR,Female,0,Yes,No,55,Yes,Yes,DSL,Yes,...,No,Yes,No,No,One year,Yes,Credit card (automatic),66.05,3462.1,No

In [15]:
df.TotalCharges.unique()

array(['880.2', '2979.5', '1647', ..., '70.1', '1319.95', '577.6'],
      dtype=object)

In [16]:
df.TotalCharges.astype(float)

ValueError: could not convert string to float: ''